const dragons = [
  {
    name: 'Plant',
    elements: ['plant'],
    images: [
      'https://vignette.wikia.nocookie.net/dragonvale/images/7/7b/PlantDragonEgg.png',
      'https://vignette.wikia.nocookie.net/dragonvale/images/b/bf/PlantDragonBaby.png',
      'https://vignette.wikia.nocookie.net/dragonvale/images/1/10/PlantDragonJuvenile.png',
      'https://vignette.wikia.nocookie.net/dragonvale/images/7/75/PlantDragonAdult.png',
      'https://vignette.wikia.nocookie.net/dragonvale/images/7/7c/PlantDragonElder.png',
    ],
    eggTime: [0, 0, 5],
    buy: 100,
    income: [0, 17, 27, 38, 48, 58, 69, 79, 89, 99, 110,
      120, 130, 141, 151, 161, 171, 182, 192, 202, 213, 223],
  },
  {
    name: 'Fire',
    elements: ['fire'],
    images: [
      'https://vignette.wikia.nocookie.net/dragonvale/images/f/f5/FireDragonEgg.png',
      'https://vignette.wikia.nocookie.net/dragonvale/images/5/54/FireDragonBaby.png',
      'https://vignette.wikia.nocookie.net/dragonvale/images/b/b5/FireDragonJuvenile.png',
      'https://vignette.wikia.nocookie.net/dragonvale/images/7/72/FireDragonAdult.png',
      'https://vignette.wikia.nocookie.net/dragonvale/images/c/ce/FireDragonElder.png',
    ],
    eggTime: [0, 5, 0],
    buy: 75,
    income: [0, 8, 12, 17, 21, 26, 30, 34, 39, 44, 48,
      53, 57, 61, 66, 70, 75, 80, 84, 89, 93, 104],
  },
  {
    name: 'Earth',
    elements: ['earth'],
    images: [
      'https://vignette.wikia.nocookie.net/dragonvale/images/e/e2/EarthDragonEgg.png',
      'https://vignette.wikia.nocookie.net/dragonvale/images/5/5c/EarthDragonBaby.png',
      'https://vignette.wikia.nocookie.net/dragonvale/images/9/9a/EarthDragonJuvenile.png',
      'https://vignette.wikia.nocookie.net/dragonvale/images/2/2c/EarthDragonAdult.png',
      'https://vignette.wikia.nocookie.net/dragonvale/images/4/48/EarthDragonElder.png',
    ],
    eggTime: [2, 0, 0],
    buy: 500,
    income: [0, 4, 6, 8, 11, 13, 15, 17, 20, 22, 24,
      26, 29, 31, 33, 35, 38, 40, 42, 44, 47, 49],
  },
  {
    name: 'Cold',
    elements: ['cold'],
    images: [
      'https://vignette.wikia.nocookie.net/dragonvale/images/0/03/ColdDragonEgg.png',
      'https://vignette.wikia.nocookie.net/dragonvale/images/5/52/ColdDragonBaby.png',
      'https://vignette.wikia.nocookie.net/dragonvale/images/e/e5/ColdDragonJuvenile.png',
      'https://vignette.wikia.nocookie.net/dragonvale/images/2/2a/ColdDragonAdult.png',
      'https://vignette.wikia.nocookie.net/dragonvale/images/7/70/ColdDragonElder.png',
    ],
    eggTime: [12, 0, 0],
    buy: 30000,
    income: [0, 5, 8, 11, 13, 16, 19, 22, 25, 28, 31,
      34, 36, 39, 42, 45, 48, 51, 54, 57, 60, 62],
  },
  {
    name: 'Evergreen',
    elements: ['plant', 'cold'],
    images: [
      'https://vignette.wikia.nocookie.net/dragonvale/images/c/c2/EvergreenDragonEgg.png',
      'https://vignette.wikia.nocookie.net/dragonvale/images/a/ad/EvergreenDragonBaby.png',
      'https://vignette.wikia.nocookie.net/dragonvale/images/7/7b/EvergreenDragonJuvenile.png',
      'https://vignette.wikia.nocookie.net/dragonvale/images/e/e2/EvergreenDragonAdult.png',
      null,
    ],
    eggTime: [10, 0, 0],
    buy: 120000,
    income: [0, 7, 11, 16, 20, 24, 28, 32, 37, 41, 45,
      49, 54, 58, 62, 66, 71, 75, 79, 83, 88, null],
  },
];

module.exports = dragons;
