const habitats = [
  {
    name: 'Plant',
    elements: ['plant'],
    image: 'https://vignette.wikia.nocookie.net/dragonvale/images/5/55/PlantHabitat2013.png',
    buildTime: [0, 0, 0],
    buy: 100,
    incomeCap: 200,
    size: [2.5, 2.5],
  },
  {
    name: 'Fire',
    elements: ['fire'],
    image: 'https://vignette.wikia.nocookie.net/dragonvale/images/d/dc/FireHabitat2013.png',
    buildTime: [0, 5, 0],
    buy: 100,
    incomeCap: 7500,
    size: [3, 1.5],
  },
  {
    name: 'Earth',
    elements: ['earth'],
    image: 'https://vignette.wikia.nocookie.net/dragonvale/images/9/96/EarthHabitat2013.png',
    buildTime: [3, 0, 0],
    buy: 500,
    incomeCap: 10000,
    size: [3, 2],
  },
  {
    name: 'Cold',
    elements: ['cold'],
    image: 'https://vignette.wikia.nocookie.net/dragonvale/images/4/42/ColdHabitat2013.png',
    buildTime: [12, 0, 0],
    buy: 20000,
    incomeCap: 15000,
    size: [3, 1.8],
  },
  {
    name: 'Lightning',
    elements: ['lightning'],
    image: 'https://vignette.wikia.nocookie.net/dragonvale/images/6/69/LightningHabitat2013.png',
    buildTime: [0, 30, 0],
    buy: 50000,
    incomeCap: 1250,
    size: [3, 2],
  },
  {
    name: 'Water',
    elements: ['water'],
    image: 'https://vignette.wikia.nocookie.net/dragonvale/images/0/08/WaterHabitat2013.png',
    buildTime: [0, 4, 0],
    buy: 100000,
    incomeCap: 15000,
    size: [3, 2],
  },
  {
    name: 'Air',
    elements: ['air'],
    image: 'https://vignette.wikia.nocookie.net/dragonvale/images/7/7c/AirHabitat2013.png',
    buildTime: [8, 0, 0],
    buy: 500000,
    incomeCap: 6000,
    size: [3, 2],
  },
  {
    name: 'Metal',
    elements: ['metal'],
    image: 'https://vignette.wikia.nocookie.net/dragonvale/images/3/38/MetalHabitat2013.png',
    buildTime: [10, 0, 0],
    buy: 1000000,
    incomeCap: 25000,
    size: [3, 2],
  },
  {
    name: 'Light',
    elements: ['light'],
    image: 'https://vignette.wikia.nocookie.net/dragonvale/images/a/ab/LightHabitat.png',
    buildTime: [16, 0, 0],
    buy: 3000000,
    incomeCap: 35000,
    size: [3, 2],
  },
  {
    name: 'Dark',
    elements: ['dark'],
    image: 'https://vignette.wikia.nocookie.net/dragonvale/images/c/c6/DarkHabitat.png',
    buildTime: [18, 0, 0],
    buy: 7500000,
    incomeCap: 50000,
    size: [3, 2],
  },
];

module.exports = habitats;
